server:
  port: 8989
  address: 0.0.0.0
  forward-headers-strategy: native
spring:
  datasource:
    url: jdbc:mysql://43.203.242.155:3306/blog
    username: kah #kim
    password: asdzxc123@ #zxcqwe456@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true            #SQL 보기 좋게 출력
        hbm2ddl.auto: update
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: true

  #default 1MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: Asia/Seoul

logging:
  file:
    name: /home/ubuntu/logfile.log #/home/kah/gitProject/back/react-spring-blog-backend/log/logfile.log #
  level:
    jhcode.blog.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  header: "Authorization"
  prefix: "Bearer "
  cookieName: "JWT-TOKEN"
  secret: eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJ1c2VyIn0I2qOfhAZMGSH1pCecUH5sV2Lg2pSWNQMPzXsMcne6NJ1SlkBoirhGAmKfTYNcRyhu6nQtRzgAd6VXyttoX9A
  tokenExpirationTime: 180

project:
  folderPath: "files/"
